version: '3.1'
services:
  nginx:
    image: nginx
    volumes:
      - .dockerconfig/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    ports:
      - 8010:80

  php:
    build: .dockerconfig/php
    volumes:
      - .dockerconfig/php/conf.d:/user/local/etc/php/conf.d
      - .:/var/www/html
    expose:
      - 9000

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'prototype'
      MYSQL_USER: 'prototype_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
